//USER PROFILE
export const ONCHANGENAMEHANDLER = "ONCHANGENAMEHANDLER";
export const ONCHANGEABOUTHANDLER = "ONCHANGEABOUTHANDLER";
export const ONCONFIRMINPUTHANDLER = "ONCONFIRMINPUTHANDLER";
export const ONCANCELINPUTHANDLER = "ONCANCELINPUTHANDLER";

//SEARCH BAR
export const ONCHANGESEARCHANGEHANDLER = "ONCHANGESEARCHANGEHANDLER";
export const DOSEARCHHANDLER = "DOSEARCHHANDLER";

//CHANGECHATBOX
export const CHANGECHATBOXONHANDLER = "CHANGECHATBOXONHANDLER";

//SENDMESSAGE
export const CHANGEMESSAGEINPUTHANDLER = "CHANGEMESSAGEINPUTHANDLER";
export const SENDMESSAGEINPUTHANDLER = "SENDMESSAGEINPUTHANDLER";
export const MESSAGESENTSUCCESS = "MESSAGESENTSUCCESS";
export const MESSAGESENTFAILED = "MESSAGESENTFAILED";