export const ONCHANGENAMEHANDLER = "ONCHANGENAMEHANDLER";
export const ONCHANGEABOUTHANDLER = "ONCHANGEABOUTHANDLER";
export const ONCONFIRMINPUTHANDLER = "ONCONFIRMINPUTHANDLER";
export const ONCANCELINPUTHANDLER = "ONCANCELINPUTHANDLER";