//USER PROFILE
export const ONCHANGENAMEHANDLER = "ONCHANGENAMEHANDLER";
export const ONCHANGEABOUTHANDLER = "ONCHANGEABOUTHANDLER";
export const ONCONFIRMINPUTHANDLER = "ONCONFIRMINPUTHANDLER";
export const ONCANCELINPUTHANDLER = "ONCANCELINPUTHANDLER";

//SEARCH BAR
export const ONCHANGESEARCHANGEHANDLER = "ONCHANGESEARCHANGEHANDLER";
export const DOSEARCHHANDLER = "DOSEARCHHANDLER";